/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 06/05/2025 00:50:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI48_VALUE                          48000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     24000000
#define MX_SYSCLKFreq_VALUE                     2097000
#define MX_HCLKFreq_Value                       2097000
#define MX_FCLKCortexFreq_Value                 2097000
#define MX_AHBFreq_Value                        2097000
#define MX_APB1Freq_Value                       2097000
#define MX_APB2Freq_Value                       2097000
#define MX_48CLKFreq_Value                      24000000
#define MX_48RNGFreq_Value                      24000000
#define MX_48USBFreq_Value                      24000000
#define MX_ADCFreq_Value                        16000000
#define MX_I2C1Freq_Value                       2097000
#define MX_LCDFreq_Value                        37000
#define MX_LPUARTFreq_Value                     2097000
#define MX_LPTIMFreq_Value                      2097000
#define MX_USART1Freq_Value                     2097000
#define MX_USART2Freq_Value                     2097000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  4000000
#define MX_TimerFreq_Value                      2097000
#define MX_VCOOutputFreq_Value                  48000000
#define MX_WatchDogFreq_Value                   37000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */
